Handles comments get and post in servlet
jyx11011/step pull request #12
Opened 2020-06-01 09:15 UTC by jyx11011

2020-06-01 13:01 UTC, anuragshirolkar commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  ArrayList<String> data = new ArrayList<>();
Let's give the variable a more specific name
```suggestion
  ArrayList<String> comments = new ArrayList<>();
```

2020-06-01 13:01 UTC, anuragshirolkar commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>  @WebServlet("/data")
"/comments" would be a better url for this api.

2020-06-02 02:04 UTC, SuyashLakhotia requested changes

2020-06-02 02:04 UTC, SuyashLakhotia commented on portfolio/src/main/webapp/index.html
>  </html>
nit: Missing \n at the EOF.

2020-06-02 02:04 UTC, SuyashLakhotia commented on portfolio/src/main/webapp/script.js
> +      for (var comment of json) {
Can this be `for (const comment of json)` instead?

2020-06-02 06:33 UTC, SuyashLakhotia approved these changes

2020-06-02 07:02 UTC, merged