Add deleting a single comment
jyx11011/step pull request #16
Opened 2020-06-03 05:19 UTC by jyx11011

Create a Comment class to store comment and its id
Add a delete button for each comment

2020-06-03 15:20 UTC, SuyashLakhotia requested changes

2020-06-03 15:20 UTC, SuyashLakhotia commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  private void deleteCommentWithId(String id) {
nit: Calling this simply "deleteComment" is probably enough.

2020-06-03 15:20 UTC, SuyashLakhotia commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  public void doDelete(HttpServletRequest request, HttpServletResponse response) throws IOException {
Can your other servlet now be deleted?

2020-06-04 02:02 UTC, jyx11011 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  public void doDelete(HttpServletRequest request, HttpServletResponse response) throws IOException {
Yes, I deleted that one.

2020-06-04 12:00 UTC, SuyashLakhotia approved these changes

2020-06-05 01:40 UTC, merged