Handle optional attendees in request
jyx11011/step pull request #28
Opened 2020-06-15 09:04 UTC by jyx11011

Add tests for optional attendees

2020-06-15 15:04 UTC, SuyashLakhotia requested changes
[redacted]

2020-06-18 03:40 UTC, jyx11011 commented
Sorry, I don't why this PR is showing all commits from the very beginning, but the file changes part is showing code different from last PR.

2020-06-19 03:48 UTC, jyx11011 commented
The commit history looks normal now.

2020-06-22 09:27 UTC, SuyashLakhotia approved these changes

2020-06-23 09:56 UTC, merged